// Package brutef32 implements brute-force k=5 Euclidean KNN over a FLAT32
// index. It is the correctness oracle for experiments: slow, but exactly
// matches the expected labels in test/test-data.json (which were themselves
// generated by exact KNN over the 14-dim vectors).
//
// The hot path reads each reference vector through an unsafe cast over the
// memory-mapped byte slice — fine on linux/amd64, where float32 alignment is
// 4 and our body starts at offset 64 (multiple of 4).
package brutef32

import (
	"fmt"
	"math"
	"unsafe"

	"rinha2026/solution/internal/idxfmt"
)

// K is the fixed neighborhood size from the spec (DETECTION_RULES.md §4).
const K = 5

// Index is a read-only view over a FLAT32 index buffer.
type Index struct {
	h       idxfmt.Header
	vecBase []byte
	lblBase []byte
	count   int
}

// Open validates the header (without re-verifying CRC, which is the index
// builder's job) and returns a queryable index over data.
func Open(data []byte) (*Index, error) {
	h, err := idxfmt.ParseHeader(data)
	if err != nil {
		return nil, err
	}
	if h.Format != idxfmt.FormatFlat32 {
		return nil, fmt.Errorf("brutef32: format %d is not FLAT32", h.Format)
	}
	need := idxfmt.HeaderSize + idxfmt.BodySize(int(h.Count))
	if len(data) < need {
		return nil, fmt.Errorf("brutef32: buffer too short (have %d, need %d)", len(data), need)
	}
	vecStart := idxfmt.HeaderSize
	vecEnd := idxfmt.HeaderSize + int(h.Count)*idxfmt.Dim*4
	return &Index{
		h:       h,
		vecBase: data[vecStart:vecEnd],
		lblBase: data[vecEnd:need],
		count:   int(h.Count),
	}, nil
}

// Count returns the number of reference entries.
func (ix *Index) Count() int { return ix.count }

// vec returns a pointer to entry i as a [14]float32. The caller must not
// mutate it (the backing memory may be mmap'd read-only).
func (ix *Index) vec(i int) *[idxfmt.Dim]float32 {
	return (*[idxfmt.Dim]float32)(unsafe.Pointer(&ix.vecBase[i*idxfmt.Dim*4]))
}

// IsFraud reports whether entry i is labeled fraud.
func (ix *Index) IsFraud(i int) bool {
	return ix.lblBase[i/8]&(1<<(i%8)) != 0
}

// SearchKNN returns the number of fraud labels (0..K) among the K nearest
// neighbors of q under squared Euclidean distance.
//
// Squared distance preserves order — no sqrt needed.
//
//go:nosplit
func (ix *Index) SearchKNN(q *[idxfmt.Dim]float32) uint8 {
	var topD [K]float32
	var topI [K]int32
	for i := 0; i < K; i++ {
		topD[i] = math.MaxFloat32
		topI[i] = -1
	}

	for i := 0; i < ix.count; i++ {
		v := ix.vec(i)
		// Unrolled 14-dim squared distance.
		d0 := v[0] - q[0]
		d1 := v[1] - q[1]
		d2 := v[2] - q[2]
		d3 := v[3] - q[3]
		d4 := v[4] - q[4]
		d5 := v[5] - q[5]
		d6 := v[6] - q[6]
		d7 := v[7] - q[7]
		d8 := v[8] - q[8]
		d9 := v[9] - q[9]
		d10 := v[10] - q[10]
		d11 := v[11] - q[11]
		d12 := v[12] - q[12]
		d13 := v[13] - q[13]
		dist :=
			d0*d0 + d1*d1 + d2*d2 + d3*d3 +
				d4*d4 + d5*d5 + d6*d6 + d7*d7 +
				d8*d8 + d9*d9 + d10*d10 + d11*d11 +
				d12*d12 + d13*d13

		if dist < topD[K-1] {
			// Linear insertion into the sorted top-K (K is 5).
			pos := K - 1
			for pos > 0 && topD[pos-1] > dist {
				topD[pos] = topD[pos-1]
				topI[pos] = topI[pos-1]
				pos--
			}
			topD[pos] = dist
			topI[pos] = int32(i)
		}
	}

	var nFraud uint8
	for k := 0; k < K; k++ {
		idx := int(topI[k])
		if idx < 0 {
			continue
		}
		if ix.IsFraud(idx) {
			nFraud++
		}
	}
	return nFraud
}
